version: 2.1

orbs:
  node: circleci/node@5.0.3
jobs:
  build_and_test:
    executor:
      name: node/default
      tag: '16.10'
    steps:
      - checkout
      - node/install-packages:
          app-dir: src
          pkg-manager: yarn
      - run:
          working_directory: src
          command: yarn lint
          name: Lint the codebase
      - run:
          working_directory: src
          command: yarn test
          name: Run YARN tests

  deploy:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - add_ssh_keys:
          # These keys come from the CircleCI App. Projects Settings -> SSH - Keys -> Additional SSH Keys.
          # The fingerprint will show up after adding a key.
          fingerprints:
            - 'd1:b2:46:4e:a2:e8:3b:10:0b:49:78:06:fa:92:25:52'
            - '0a:51:56:fd:81:33:42:19:7d:59:13:af:43:1f:cf:1e'
      - run:
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              ssh-keyscan testing.govstack.global >> ~/.ssh/known_hosts
            elif [ "${CIRCLE_BRANCH}" == "develop" ]; then
              ssh-keyscan staging.testing.govstack.global >> ~/.ssh/known_hosts
            fi
          name: Add known host for SSH
      - run:
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              bash deployment/deploy.sh prod
            elif [ "${CIRCLE_BRANCH}" == "develop" ]; then
              bash deployment/deploy.sh staging
            fi
          name: Deploy based on branch

workflows:
  build_test_deploy:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test
          filters:
            branches:
              only:
                - main
                - develop
